# -*- coding: utf-8 -*-
"""
REDLINE NEXOR ERP - Ana Uygulama
Modüler yapı ile organize edilmiş ERP sistemi

Kullanım:
    python main.py              # Normal başlatma
    python main.py --setup      # Veritabanı ayarları ile başlat
    python main.py --reset-db   # DB ayarlarını sıfırla ve wizard aç
"""

# ============================================
# VTK Hata Bastırma (Auto-Generated by Build Manager v5.0)
# ============================================
import os
import warnings

os.environ['VTKRENDERINGBACKEND_OVERRIDE'] = 'OSMesa'
os.environ['VTK_SILENCE_GET_VOID_POINTER_WARNINGS'] = '1'
os.environ['VTK_NO_GRAPHICS'] = '1'
os.environ['QT_LOGGING_RULES'] = '*.debug=false;qt.qpa.*=false'

warnings.filterwarnings('ignore', category=DeprecationWarning)
warnings.filterwarnings('ignore', category=RuntimeWarning)

try:
    import vtk
    vtk.vtkObject.GlobalWarningDisplayOff()
except ImportError:
    pass
# ============================================

import sys
import json
import argparse
import traceback
from pathlib import Path

import logging

from PySide6.QtWidgets import (
    QApplication, QMainWindow, QWidget, QVBoxLayout, QHBoxLayout,
    QStackedWidget, QMessageBox, QTextEdit, QDialog, QPushButton,
    QGraphicsOpacityEffect
)
from PySide6.QtGui import QFont, QIcon
from PySide6.QtCore import Qt, QPropertyAnimation, QEasingCurve

logging.basicConfig(
    level=logging.INFO,
    format="[%(levelname)s] %(name)s: %(message)s"
)
logger = logging.getLogger("nexor")

from config import APP_NAME, SETTINGS_FILE
from version import VERSION, get_full_version
from themes import build_theme
from core.menu_structure import MENU_STRUCTURE, get_page_title
from components import Sidebar, Header
from dialogs import ModernLoginDialog
from dialogs.splash_screen import NexorSplashScreen

# Yeni modül sistemi
from modules import PageRegistry
from modules.sistem import SistemAyarPage

# Geriye dönük uyumluluk için PAGE_CLASSES
PAGE_CLASSES = PageRegistry.all_pages()

# Skeleton loader
from components.skeleton_loader import SkeletonCardLoader


# =============================================================================
# LAZY PAGE PROXY
# =============================================================================

class LazyPageProxy(QWidget):
    """
    Hafif proxy widget - gercek sayfayi ilk gosterildiginde olusturur.
    Stack'e eklenir ama icerik sadece ensure_loaded() cagrildiginda yaratilir.
    """

    def __init__(self, page_id: str, page_class, theme: dict):
        super().__init__()
        self.page_id = page_id
        self._page_class = page_class
        self._theme = theme
        self._real_page = None
        self._loaded = False

        # Skeleton placeholder
        self._layout = QVBoxLayout(self)
        self._layout.setContentsMargins(0, 0, 0, 0)
        self._skeleton = SkeletonCardLoader()
        bg = theme.get('bg_hover', theme.get('bg_card', '#1E1E1E'))
        shimmer = theme.get('border', theme.get('border_light', '#2A2A2A'))
        self._skeleton.set_theme_colors(bg, shimmer)
        self._layout.addWidget(self._skeleton)

    @property
    def loaded(self) -> bool:
        return self._loaded

    @property
    def real_page(self):
        return self._real_page

    def ensure_loaded(self) -> QWidget:
        """Gercek sayfayi olustur (henuz olusturulmadiysa)"""
        if self._loaded:
            return self._real_page
        try:
            self._real_page = self._page_class(self._theme)
            if self._skeleton:
                self._skeleton.stop()
                self._skeleton.setParent(None)
                self._skeleton.deleteLater()
                self._skeleton = None
            self._layout.addWidget(self._real_page)
            self._loaded = True
            logger.info("Sayfa yuklendi: %s", self.page_id)
        except Exception as e:
            logger.error("Sayfa yuklenemedi (%s): %s", self.page_id, e)
            raise
        return self._real_page

    def update_stored_theme(self, theme: dict):
        """Tema degistiginde sayfayi yeniden olusturmak uzere isaretler.

        Sayfalar inline setStyleSheet() ile olusturuldugundan,
        tema degisikligi ancak sayfayi yeniden olusturarak uygulanabilir.
        """
        self._theme = theme
        if self._loaded and self._real_page:
            # Sayfayi yok et ve lazy-load'a geri dondur
            self._real_page.setParent(None)
            self._real_page.deleteLater()
            self._real_page = None
            self._loaded = False
            self._pending_recreate = True
            logger.info("Sayfa tema icin yeniden olusturulacak: %s", self.page_id)
        elif self._skeleton:
            bg = theme.get('bg_hover', theme.get('bg_card', '#1E1E1E'))
            shimmer = theme.get('border', theme.get('border_light', '#2A2A2A'))
            self._skeleton.set_theme_colors(bg, shimmer)

    def _ensure_skeleton(self):
        """Skeleton placeholder'i geri yukle (sayfa yeniden olusturulacaksa)"""
        if self._skeleton is None:
            self._skeleton = SkeletonCardLoader()
            bg = self._theme.get('bg_hover', self._theme.get('bg_card', '#1E1E1E'))
            shimmer = self._theme.get('border', self._theme.get('border_light', '#2A2A2A'))
            self._skeleton.set_theme_colors(bg, shimmer)
            self._layout.addWidget(self._skeleton)

# Themed MessageBox - QMessageBox'ı tema uyumlu hale getirir
try:
    from core.themed_messagebox import patch_messagebox, update_theme as update_messagebox_theme
    THEMED_MESSAGEBOX_AVAILABLE = True
except ImportError:
    THEMED_MESSAGEBOX_AVAILABLE = False
    logger.warning("Themed MessageBox modülü bulunamadı.")

# PDKS Servisi (opsiyonel - eğer modül yoksa sessizce geç)
try:
    from core.pdks_reader_service import get_pdks_service, stop_pdks_service
    PDKS_SERVICE_AVAILABLE = True
except ImportError:
    PDKS_SERVICE_AVAILABLE = False
    logger.warning("PDKS Reader Service bulunamadı, servis devre dışı.")

# PLC Sync Servisi (opsiyonel - KAPLAMA DB'den veri çekme)
try:
    from core.plc_sync_service import get_plc_sync_service, stop_plc_sync_service, is_plc_sync_running
    PLC_SYNC_AVAILABLE = True
except ImportError:
    PLC_SYNC_AVAILABLE = False
    logger.warning("PLC Sync Service bulunamadı, servis devre dışı.")


def parse_arguments():
    """Komut satırı argümanlarını parse et"""
    parser = argparse.ArgumentParser(
        description='NEXOR ERP - Kurumsal Kaynak Planlama Sistemi',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Örnekler:
  python main.py              Normal başlatma
  python main.py --setup      Veritabanı ayarları ile başlat
  python main.py --reset-db   DB ayarlarını sıfırla
        """
    )
    parser.add_argument(
        '--setup', '-s',
        action='store_true',
        help='Veritabanı ayar wizard\'ını aç'
    )
    parser.add_argument(
        '--reset-db',
        action='store_true',
        help='Veritabanı ayarlarını sıfırla ve wizard aç'
    )
    parser.add_argument(
        '--version', '-v',
        action='version',
        version=f'NEXOR ERP {VERSION}'
    )
    return parser.parse_args()


def check_database_connection() -> tuple[bool, str]:
    """
    Veritabanı bağlantısını kontrol et
    Returns: (başarılı, hata_mesajı)
    """
    try:
        from core.external_config import config_manager
        
        # Config dosyası var mı?
        if config_manager.needs_setup():
            return False, "Veritabanı ayarları yapılmamış"
        
        # Bağlantı testi
        success, message = config_manager.test_connection()
        return success, message
        
    except ImportError:
        # external_config yoksa config.py'den dene
        try:
            from core.database import get_db_connection
            conn = get_db_connection()
            if conn:
                conn.close()
                return True, "OK"
            return False, "Bağlantı kurulamadı"
        except Exception as e:
            return False, str(e)
    except Exception as e:
        return False, str(e)


def show_setup_wizard(app: QApplication, force: bool = False) -> bool:
    """
    Setup wizard'ı göster
    Returns: True = devam et, False = çıkış
    """
    try:
        from dialogs.setup_wizard import SetupWizard
        
        wizard = SetupWizard()
        result = wizard.exec()
        
        if result == QDialog.Accepted:
            logger.info("Veritabanı ayarları kaydedildi")
            # Config'i yeniden yükle
            try:
                from core.external_config import config_manager
                config_manager.reload()
            except:
                pass
            return True
        else:
            if force:
                # Zorunlu kurulum, iptal edilemez
                QMessageBox.warning(
                    None,
                    "Kurulum Gerekli",
                    "Veritabanı ayarları yapılmadan uygulama çalışamaz.\n"
                    "Lütfen ayarları yapın veya uygulamayı kapatın."
                )
                return show_setup_wizard(app, force=True)
            return False
            
    except Exception as e:
        logger.error("Setup wizard hatası: %s", e)
        QMessageBox.critical(
            None,
            "Hata",
            f"Setup wizard açılamadı:\n{e}"
        )
        return False


class ErrorDialog(QDialog):
    """Hata mesajı dialog"""
    
    def __init__(self, error_title: str, error_message: str, parent=None):
        super().__init__(parent)
        self.setWindowTitle(f"HATA: {error_title}")
        self.setMinimumSize(800, 600)
        self.setWindowFlags(self.windowFlags() | Qt.WindowStaysOnTopHint)
        
        layout = QVBoxLayout(self)
        
        # Hata mesajı
        error_text = QTextEdit()
        error_text.setReadOnly(True)
        error_text.setPlainText(error_message)
        error_text.setStyleSheet("""
            QTextEdit {
                background: #1e1e1e;
                color: #ff6b6b;
                font-family: 'Courier New', monospace;
                font-size: 11px;
                padding: 10px;
            }
        """)
        layout.addWidget(error_text)
        
        # Butonlar
        btn_layout = QHBoxLayout()
        
        copy_btn = QPushButton("Kopyala")
        copy_btn.clicked.connect(lambda: QApplication.clipboard().setText(error_message))
        btn_layout.addWidget(copy_btn)
        
        btn_layout.addStretch()
        
        close_btn = QPushButton("Kapat")
        close_btn.clicked.connect(self.accept)
        btn_layout.addWidget(close_btn)
        
        layout.addLayout(btn_layout)


def show_error_dialog(title: str, error: Exception):
    """Hata dialog göster"""
    error_msg = f"""
╔══════════════════════════════════════════════════════════════╗
║                     REDLINE NEXOR ERP                        ║
║                        HATA RAPORU                           ║
╚══════════════════════════════════════════════════════════════╝

HATA TİPİ: {type(error).__name__}
HATA MESAJI: {str(error)}

─────────────────────────────────────────────────────────────

DETAYLI HATA:
{traceback.format_exc()}

─────────────────────────────────────────────────────────────

ÇÖZÜM ÖNERİLERİ:

1. TEMA HATASI İSE:
   - themes.py dosyasının doğru kopyalandığından emin olun
   - Dosyayı açın ve "build_theme" fonksiyonunu kontrol edin

2. IMPORT HATASI İSE:
   - Eksik modülü yükleyin: pip install [modül_adı]
   - __pycache__ klasörlerini silin ve tekrar deneyin

3. DATABASE HATASI İSE:
   - config.py'de veritabanı ayarlarını kontrol edin
   - SQL Server'ın çalıştığından emin olun

4. DOSYA BULUNAMADI HATASI İSE:
   - Logo dosyalarının assets/ klasöründe olduğunu kontrol edin
   - Dosya yollarını kontrol edin

Bu hatayı Kopyala butonuna basarak kopyalayabilir ve 
destek ekibiyle paylaşabilirsiniz.

Email: support@redlinecreative.com
"""
    
    dialog = ErrorDialog(title, error_msg)
    dialog.exec()


def get_icon_path() -> str:
    """Icon dosyasının yolunu döndürür (EXE ve dev modunda çalışır)"""
    try:
        if getattr(sys, 'frozen', False):
            # PyInstaller ile paketlenmiş
            base_path = Path(sys._MEIPASS)
        else:
            # Development modu
            base_path = Path(__file__).parent
        
        icon_path = base_path / "assets" / "icon.ico"
        return str(icon_path) if icon_path.exists() else ""
    except Exception as e:
        logger.warning("Icon yolu alınamadı: %s", e)
        return ""


class MainWindow(QMainWindow):
    """Ana Pencere"""
    
    def __init__(self, user_data: dict):
        super().__init__()
        self.user_data = user_data
        self.pages = {}
        
        try:
            self._load_settings()
        except Exception as e:
            logger.error("Ayarlar yüklenemedi: %s", e)
            # Varsayılan ayarlar
            self.current_mode = "dark"
            self.current_color = "nexor"
            self.expanded_mode = True
            self.logo_path = None
        
        try:
            self.theme = build_theme(self.current_mode, self.current_color)
        except Exception as e:
            logger.error("Tema oluşturulamadı: %s", e)
            show_error_dialog("Tema Hatası", e)
            raise
        
        self.setWindowTitle(APP_NAME)
        self.setMinimumSize(1280, 800)
        
        # Window icon ayarla
        try:
            icon_path = get_icon_path()
            if icon_path:
                self.setWindowIcon(QIcon(icon_path))
        except Exception as e:
            logger.warning("Icon ayarlanamadı: %s", e)
        
        try:
            self._setup_ui()
            self._show_page("dashboard")
        except Exception as e:
            logger.error("UI oluşturulamadı: %s", e)
            show_error_dialog("UI Hatası", e)
            raise
    
    def _load_settings(self):
        """Kaydedilmiş ayarları yükle"""
        self.current_mode = "dark"
        self.current_color = "nexor"  # "blue" yerine "nexor"
        self.expanded_mode = True
        self.logo_path = None
        
        try:
            if SETTINGS_FILE.exists():
                with open(SETTINGS_FILE, encoding='utf-8') as f:
                    data = json.load(f)
                    self.current_mode = data.get("mode", "dark")
                    self.current_color = data.get("color", "nexor")
                    self.expanded_mode = data.get("expanded", True)
                    self.logo_path = data.get("logo", None)
        except Exception as e:
            logger.warning("Ayarlar yüklenemedi: %s", e)
    
    def _save_settings(self):
        """Ayarları kaydet"""
        try:
            SETTINGS_FILE.parent.mkdir(parents=True, exist_ok=True)
            with open(SETTINGS_FILE, 'w', encoding='utf-8') as f:
                json.dump({
                    "mode": self.current_mode,
                    "color": self.current_color,
                    "expanded": self.expanded_mode,
                    "logo": self.logo_path
                }, f)
        except Exception as e:
            logger.warning("Ayarlar kaydedilemedi: %s", e)
    
    def _setup_ui(self):
        """UI oluştur"""
        try:
            self._apply_theme()
        except Exception as e:
            logger.error("Tema uygulanamadı: %s", e)
            raise
        
        self.central = QWidget()
        self.setCentralWidget(self.central)
        
        self.main_layout = QHBoxLayout(self.central)
        self.main_layout.setContentsMargins(0, 0, 0, 0)
        self.main_layout.setSpacing(0)
        
        # Sidebar
        try:
            self.sidebar = Sidebar(
                self.theme, 
                self.expanded_mode, 
                self.logo_path,
                is_dark_mode=(self.current_mode == "dark")
            )
            self.sidebar.menu_clicked.connect(self._on_menu_clicked)
            self.sidebar.theme_toggle_requested.connect(self._toggle_theme)
            if self.logo_path:
                self.sidebar.set_logo(self.logo_path)
            self.main_layout.addWidget(self.sidebar)
        except Exception as e:
            logger.error("Sidebar oluşturulamadı: %s", e)
            show_error_dialog("Sidebar Hatası", e)
            raise
        
        # Sağ panel
        self.right_panel = QWidget()
        r_layout = QVBoxLayout(self.right_panel)
        r_layout.setContentsMargins(0, 0, 0, 0)
        r_layout.setSpacing(0)
        
        # Header
        try:
            self.header = Header(self.theme, self.user_data)
            self.header.toggle_sidebar.connect(self._toggle_sidebar)
            r_layout.addWidget(self.header)
        except Exception as e:
            logger.error("Header oluşturulamadı: %s", e)
            show_error_dialog("Header Hatası", e)
            raise
        
        # Stack (sayfalar)
        self.stack = QStackedWidget()
        self.stack.setStyleSheet(f"background: {self.theme['bg_main']};")
        r_layout.addWidget(self.stack)
        
        self.main_layout.addWidget(self.right_panel, 1)
        
        try:
            self._create_pages()
        except Exception as e:
            logger.error("Sayfalar oluşturulamadı: %s", e)
            show_error_dialog("Sayfa Oluşturma Hatası", e)
            raise

        # PLC Sync servisini arka planda başlat
        if PLC_SYNC_AVAILABLE:
            try:
                self._plc_service = get_plc_sync_service()
                logger.info("PLC Sync servisi arka planda başlatıldı")
            except Exception as e:
                logger.warning("PLC Sync servisi başlatılamadı: %s", e)

    def _apply_theme(self):
        """Temayı uygula"""
        try:
            t = self.theme
            
            # QApplication seviyesinde global stil (QMessageBox, QDialog vs.)
            app = QApplication.instance()
            if app:
                # Fusion style kullan - palette'i daha iyi uygular
                app.setStyle("Fusion")
                
                # QPalette ile sistem renklerini ayarla
                from PySide6.QtGui import QPalette, QColor
                palette = QPalette()
                
                # Renk değişkenleri
                bg_window = QColor(t['bg_card'])
                bg_base = QColor(t['bg_input'])
                bg_alt = QColor(t['bg_hover'])
                bg_button = QColor(t['bg_input'])
                text_color = QColor(t['text'])
                text_secondary = QColor(t.get('text_secondary', '#888888'))
                text_disabled = QColor(t.get('text_disabled', '#555555'))
                border_color = QColor(t['border'])
                primary = QColor(t['primary'])
                tooltip_bg = QColor(t.get('bg_tooltip', t['bg_card']))
                # Light modda tooltip bg koyu, text beyaz olmali
                tooltip_text = QColor(t.get('text_inverse', '#FFFFFF')) if t.get('mode') == 'light' else text_color
                
                # === ACTIVE STATE ===
                palette.setColor(QPalette.Active, QPalette.Window, bg_window)
                palette.setColor(QPalette.Active, QPalette.WindowText, text_color)
                palette.setColor(QPalette.Active, QPalette.Base, bg_base)
                palette.setColor(QPalette.Active, QPalette.AlternateBase, bg_alt)
                palette.setColor(QPalette.Active, QPalette.Text, text_color)
                palette.setColor(QPalette.Active, QPalette.Button, bg_button)
                palette.setColor(QPalette.Active, QPalette.ButtonText, text_color)
                palette.setColor(QPalette.Active, QPalette.BrightText, QColor('#FFFFFF'))
                palette.setColor(QPalette.Active, QPalette.Highlight, primary)
                palette.setColor(QPalette.Active, QPalette.HighlightedText, QColor('#FFFFFF'))
                palette.setColor(QPalette.Active, QPalette.Link, primary)
                palette.setColor(QPalette.Active, QPalette.LinkVisited, primary)
                palette.setColor(QPalette.Active, QPalette.ToolTipBase, tooltip_bg)
                palette.setColor(QPalette.Active, QPalette.ToolTipText, tooltip_text)
                palette.setColor(QPalette.Active, QPalette.PlaceholderText, text_secondary)
                palette.setColor(QPalette.Active, QPalette.Light, bg_alt)
                palette.setColor(QPalette.Active, QPalette.Midlight, bg_alt)
                palette.setColor(QPalette.Active, QPalette.Dark, border_color)
                palette.setColor(QPalette.Active, QPalette.Mid, border_color)
                palette.setColor(QPalette.Active, QPalette.Shadow, QColor('#000000'))
                
                # === INACTIVE STATE (aynı renkler) ===
                palette.setColor(QPalette.Inactive, QPalette.Window, bg_window)
                palette.setColor(QPalette.Inactive, QPalette.WindowText, text_color)
                palette.setColor(QPalette.Inactive, QPalette.Base, bg_base)
                palette.setColor(QPalette.Inactive, QPalette.AlternateBase, bg_alt)
                palette.setColor(QPalette.Inactive, QPalette.Text, text_color)
                palette.setColor(QPalette.Inactive, QPalette.Button, bg_button)
                palette.setColor(QPalette.Inactive, QPalette.ButtonText, text_color)
                palette.setColor(QPalette.Inactive, QPalette.BrightText, QColor('#FFFFFF'))
                palette.setColor(QPalette.Inactive, QPalette.Highlight, primary)
                palette.setColor(QPalette.Inactive, QPalette.HighlightedText, QColor('#FFFFFF'))
                palette.setColor(QPalette.Inactive, QPalette.Link, primary)
                palette.setColor(QPalette.Inactive, QPalette.LinkVisited, primary)
                palette.setColor(QPalette.Inactive, QPalette.ToolTipBase, tooltip_bg)
                palette.setColor(QPalette.Inactive, QPalette.ToolTipText, tooltip_text)
                palette.setColor(QPalette.Inactive, QPalette.PlaceholderText, text_secondary)
                palette.setColor(QPalette.Inactive, QPalette.Light, bg_alt)
                palette.setColor(QPalette.Inactive, QPalette.Midlight, bg_alt)
                palette.setColor(QPalette.Inactive, QPalette.Dark, border_color)
                palette.setColor(QPalette.Inactive, QPalette.Mid, border_color)
                palette.setColor(QPalette.Inactive, QPalette.Shadow, QColor('#000000'))
                
                # === DISABLED STATE ===
                palette.setColor(QPalette.Disabled, QPalette.Window, bg_window)
                palette.setColor(QPalette.Disabled, QPalette.WindowText, text_disabled)
                palette.setColor(QPalette.Disabled, QPalette.Base, bg_base)
                palette.setColor(QPalette.Disabled, QPalette.AlternateBase, bg_alt)
                palette.setColor(QPalette.Disabled, QPalette.Text, text_disabled)
                palette.setColor(QPalette.Disabled, QPalette.Button, bg_button)
                palette.setColor(QPalette.Disabled, QPalette.ButtonText, text_disabled)
                palette.setColor(QPalette.Disabled, QPalette.BrightText, text_disabled)
                palette.setColor(QPalette.Disabled, QPalette.Highlight, border_color)
                palette.setColor(QPalette.Disabled, QPalette.HighlightedText, text_disabled)
                palette.setColor(QPalette.Disabled, QPalette.Link, text_disabled)
                palette.setColor(QPalette.Disabled, QPalette.LinkVisited, text_disabled)
                palette.setColor(QPalette.Disabled, QPalette.ToolTipBase, tooltip_bg)
                palette.setColor(QPalette.Disabled, QPalette.ToolTipText, tooltip_text)
                palette.setColor(QPalette.Disabled, QPalette.PlaceholderText, text_disabled)
                palette.setColor(QPalette.Disabled, QPalette.Light, bg_alt)
                palette.setColor(QPalette.Disabled, QPalette.Midlight, bg_alt)
                palette.setColor(QPalette.Disabled, QPalette.Dark, border_color)
                palette.setColor(QPalette.Disabled, QPalette.Mid, border_color)
                palette.setColor(QPalette.Disabled, QPalette.Shadow, QColor('#000000'))
                
                app.setPalette(palette)
                
                # Ek stylesheet - daha spesifik seçiciler
                # QMessageBox için güçlendirilmiş stiller (tüm child widget'lar dahil)
                app.setStyleSheet(f"""
                    /* ============================================ */
                    /* QMessageBox - Tam Tema Desteği               */
                    /* ============================================ */
                    QMessageBox {{
                        background-color: {t['bg_card']};
                        color: {t['text']};
                        border: 1px solid {t['border']};
                    }}
                    QMessageBox * {{
                        background-color: transparent;
                        color: {t['text']};
                    }}
                    QMessageBox QLabel {{
                        color: {t['text']};
                        font-size: 13px;
                        padding: 8px;
                        background-color: transparent;
                        min-width: 250px;
                    }}
                    QMessageBox QLabel#qt_msgbox_label {{
                        color: {t['text']};
                        font-size: 13px;
                        background-color: transparent;
                    }}
                    QMessageBox QLabel#qt_msgbox_informativelabel {{
                        color: {t['text_secondary']};
                        font-size: 12px;
                        background-color: transparent;
                    }}
                    QMessageBox QPushButton {{
                        background-color: {t['bg_input']};
                        color: {t['text']};
                        border: 1px solid {t['border']};
                        border-radius: 6px;
                        padding: 8px 20px;
                        min-width: 80px;
                        min-height: 32px;
                        font-size: 13px;
                        font-weight: 500;
                    }}
                    QMessageBox QPushButton:hover {{
                        background-color: {t['bg_hover']};
                        border-color: {t['primary']};
                    }}
                    QMessageBox QPushButton:pressed {{
                        background-color: {t['primary']};
                        color: white;
                    }}
                    QMessageBox QPushButton:default {{
                        background-color: {t['primary']};
                        color: white;
                        border-color: {t['primary']};
                    }}
                    QMessageBox QPushButton:default:hover {{
                        background-color: {t['primary_hover']};
                    }}
                    QMessageBox QDialogButtonBox {{
                        background-color: transparent;
                    }}
                    
                    /* ============================================ */
                    /* QDialog - Genel Dialog Stili                 */
                    /* ============================================ */
                    QDialog {{
                        background-color: {t['bg_card']};
                        color: {t['text']};
                    }}
                    QDialog * {{
                        color: {t['text']};
                    }}
                    QDialog QLabel {{
                        color: {t['text']};
                        background-color: transparent;
                    }}
                    QDialog QLineEdit {{
                        background-color: {t['bg_input']};
                        color: {t['text']};
                        border: 1px solid {t['border']};
                        border-radius: 6px;
                        padding: 8px;
                        selection-background-color: {t['primary']};
                    }}
                    QDialog QLineEdit:focus {{
                        border-color: {t['primary']};
                    }}
                    QDialog QTextEdit, QDialog QPlainTextEdit {{
                        background-color: {t['bg_input']};
                        color: {t['text']};
                        border: 1px solid {t['border']};
                        border-radius: 6px;
                        padding: 8px;
                    }}
                    QDialog QComboBox {{
                        background-color: {t['bg_input']};
                        color: {t['text']};
                        border: 1px solid {t['border']};
                        border-radius: 6px;
                        padding: 6px 12px;
                        min-height: 24px;
                    }}
                    QDialog QComboBox:hover {{
                        border-color: {t['primary']};
                    }}
                    QDialog QComboBox::drop-down {{
                        border: none;
                        width: 24px;
                    }}
                    QDialog QComboBox QAbstractItemView {{
                        background-color: {t['bg_dropdown']};
                        color: {t['text']};
                        border: 1px solid {t['border']};
                        selection-background-color: {t['primary']};
                    }}
                    QDialog QPushButton {{
                        background-color: {t['bg_input']};
                        color: {t['text']};
                        border: 1px solid {t['border']};
                        border-radius: 6px;
                        padding: 8px 16px;
                        min-width: 80px;
                    }}
                    QDialog QPushButton:hover {{
                        background-color: {t['bg_hover']};
                        border-color: {t['primary']};
                    }}
                    QDialog QPushButton:pressed {{
                        background-color: {t['primary']};
                        color: white;
                    }}
                    QDialog QCheckBox, QDialog QRadioButton {{
                        color: {t['text']};
                        spacing: 8px;
                    }}
                    QDialog QGroupBox {{
                        color: {t['text']};
                        border: 1px solid {t['border']};
                        border-radius: 6px;
                        margin-top: 12px;
                        padding-top: 12px;
                    }}
                    QDialog QGroupBox::title {{
                        color: {t['text']};
                        subcontrol-origin: margin;
                        left: 10px;
                        padding: 0 5px;
                    }}
                    
                    /* ============================================ */
                    /* QToolTip                                     */
                    /* ============================================ */
                    QToolTip {{
                        background-color: {t['bg_tooltip']};
                        color: {t.get('text_inverse', '#FFFFFF') if t.get('mode') == 'light' else t['text']};
                        border: 1px solid {t['border']};
                        padding: 6px 10px;
                        border-radius: 4px;
                        font-size: 12px;
                    }}
                    
                    /* ============================================ */
                    /* QInputDialog                                 */
                    /* ============================================ */
                    QInputDialog {{
                        background-color: {t['bg_card']};
                    }}
                    QInputDialog QLabel {{
                        color: {t['text']};
                    }}
                    QInputDialog QLineEdit {{
                        background-color: {t['bg_input']};
                        color: {t['text']};
                        border: 1px solid {t['border']};
                        border-radius: 6px;
                        padding: 8px;
                    }}
                    QInputDialog QLineEdit:focus {{
                        border-color: {t['primary']};
                    }}
                    QInputDialog QPushButton {{
                        background-color: {t['bg_input']};
                        color: {t['text']};
                        border: 1px solid {t['border']};
                        border-radius: 6px;
                        padding: 8px 16px;
                        min-width: 80px;
                    }}
                    QInputDialog QPushButton:hover {{
                        background-color: {t['bg_hover']};
                        border-color: {t['primary']};
                    }}
                    
                    /* ============================================ */
                    /* QFileDialog                                  */
                    /* ============================================ */
                    QFileDialog {{
                        background-color: {t['bg_card']};
                    }}
                    QFileDialog QLabel {{
                        color: {t['text']};
                    }}
                    QFileDialog QLineEdit {{
                        background-color: {t['bg_input']};
                        color: {t['text']};
                        border: 1px solid {t['border']};
                        border-radius: 4px;
                        padding: 6px;
                    }}
                    QFileDialog QTreeView, QFileDialog QListView {{
                        background-color: {t['bg_input']};
                        color: {t['text']};
                        border: 1px solid {t['border']};
                        selection-background-color: {t['primary']};
                    }}
                    QFileDialog QPushButton {{
                        background-color: {t['bg_input']};
                        color: {t['text']};
                        border: 1px solid {t['border']};
                        border-radius: 4px;
                        padding: 6px 12px;
                    }}
                    QFileDialog QPushButton:hover {{
                        background-color: {t['bg_hover']};
                    }}
                """)
            
            # Themed MessageBox temasını güncelle
            if THEMED_MESSAGEBOX_AVAILABLE:
                update_messagebox_theme(t)
            
            # MainWindow stili
            self.setStyleSheet(f"""
                QMainWindow {{ 
                    background-color: {t['bg_main']}; 
                }}
            """)
            
            # Sağ panel ve stack varsa onları da güncelle
            if hasattr(self, 'right_panel'):
                self.right_panel.setStyleSheet(f"background-color: {t['bg_main']};")
            if hasattr(self, 'stack'):
                self.stack.setStyleSheet(f"background-color: {t['bg_main']};")
        except Exception as e:
            logger.error("Tema uygulanamadı: %s", e)
            raise
    
    def _create_pages(self):
        """Tüm sayfaları lazy proxy olarak oluştur"""
        # Sistem Ayarları özel (signal bağlantısı gerekiyor) - hemen yükle
        try:
            self.settings_page = SistemAyarPage(
                self.theme,
                self.current_mode,
                self.current_color,
                self.expanded_mode,
                self.logo_path
            )
            self.settings_page.settings_changed.connect(self._on_settings_changed)
            self.pages["sistem_ayar"] = self.settings_page
            self.stack.addWidget(self.settings_page)
        except Exception as e:
            logger.warning("Sistem Ayarları sayfası oluşturulamadı: %s", e)

        # Diğer sayfalar - lazy proxy ile
        for page_id, page_class in PAGE_CLASSES.items():
            if page_id != "sistem_ayar":
                try:
                    proxy = LazyPageProxy(page_id, page_class, self.theme)
                    self.pages[page_id] = proxy
                    self.stack.addWidget(proxy)
                except Exception as e:
                    logger.warning("Sayfa proxy oluşturma hatası (%s): %s", page_id, e)
    
    def _on_menu_clicked(self, menu_id: str):
        """Menü tıklandığında"""
        try:
            self._show_page(menu_id)
        except Exception as e:
            logger.error("Sayfa gösterilemedi (%s): %s", menu_id, e)
            QMessageBox.warning(self, "Hata", f"Sayfa açılamadı: {menu_id}\n\n{str(e)}")
    
    def _show_page(self, page_id: str):
        """Sayfayı göster (lazy load + fade animasyonu)"""
        if page_id not in self.pages:
            return

        try:
            widget = self.pages[page_id]

            # LazyPageProxy ise gercek sayfayi olustur
            if isinstance(widget, LazyPageProxy):
                widget.ensure_loaded()

            # Fade animasyonlu gecis
            self._animated_switch(widget)

            self.header.set_title(get_page_title(page_id))

            # Sayfa refresh metodu varsa çağır
            real = widget.real_page if isinstance(widget, LazyPageProxy) else widget
            if real and hasattr(real, 'on_page_shown'):
                real.on_page_shown()
        except Exception as e:
            logger.error("Sayfa gösterilemedi: %s", e)
            raise

    def _animated_switch(self, target_widget: QWidget):
        """Fade-out → switch → fade-in gecisi"""
        current = self.stack.currentWidget()

        if current is None or current is target_widget:
            self.stack.setCurrentWidget(target_widget)
            return

        # Fade-out mevcut sayfa
        effect = QGraphicsOpacityEffect(current)
        current.setGraphicsEffect(effect)

        fade_out = QPropertyAnimation(effect, b"opacity")
        fade_out.setDuration(120)
        fade_out.setStartValue(1.0)
        fade_out.setEndValue(0.0)
        fade_out.setEasingCurve(QEasingCurve.OutQuad)

        def on_fade_out_done():
            current.setGraphicsEffect(None)
            self.stack.setCurrentWidget(target_widget)

            # Fade-in yeni sayfa
            effect_in = QGraphicsOpacityEffect(target_widget)
            target_widget.setGraphicsEffect(effect_in)

            fade_in = QPropertyAnimation(effect_in, b"opacity")
            fade_in.setDuration(120)
            fade_in.setStartValue(0.0)
            fade_in.setEndValue(1.0)
            fade_in.setEasingCurve(QEasingCurve.InQuad)
            fade_in.finished.connect(lambda: target_widget.setGraphicsEffect(None))
            fade_in.start()
            # prevent GC
            target_widget._fade_anim = fade_in

        fade_out.finished.connect(on_fade_out_done)
        fade_out.start()
        # prevent GC
        current._fade_anim = fade_out
    
    def _toggle_theme(self):
        """Sidebar'daki tema butonuna basıldığında - Dark/Light değiştir"""
        try:
            # Modu değiştir
            new_mode = "light" if self.current_mode == "dark" else "dark"
            self.current_mode = new_mode

            # Temayı yeniden oluştur
            self.theme = build_theme(self.current_mode, self.current_color)

            # Tüm bileşenleri güncelle
            self._apply_theme()

            # Sidebar
            self.sidebar.set_dark_mode(self.current_mode == "dark")
            self.sidebar.update_theme(self.theme)

            # Header
            self.header.update_theme(self.theme)

            # Sayfaların temasını güncelle (yeniden oluşturmadan)
            self._update_page_themes()

            # Sistem ayarları sayfasını da güncelle
            if hasattr(self, 'settings_page'):
                self.settings_page.current_mode = self.current_mode
                if hasattr(self.settings_page, 'mode_combo'):
                    index = 0 if self.current_mode == "dark" else 1
                    self.settings_page.mode_combo.setCurrentIndex(index)

            # Ayarları kaydet
            self._save_settings()
        except Exception as e:
            logger.error("Tema değiştirilemedi: %s", e)
            QMessageBox.critical(self, "Tema Hatası", f"Tema değiştirilemedi:\n\n{str(e)}")
    
    def _update_page_themes(self):
        """Tema degistiginde tum sayfalari guncelle.

        LazyPageProxy sayfalarini yeniden olusturmak uzere isaretler.
        Aktif gorunen sayfayi hemen yeniden olusturur.
        """
        try:
            current_widget = self.stack.currentWidget() if hasattr(self, 'stack') else None

            for page_id, widget in self.pages.items():
                if isinstance(widget, LazyPageProxy):
                    widget.update_stored_theme(self.theme)
                    # Aktif gorunen sayfa ise hemen yeniden olustur
                    if widget is current_widget and not widget.loaded:
                        widget.ensure_loaded()
                elif page_id == "sistem_ayar":
                    # Sistem ayarları sayfası özel - kendi update_theme'i var
                    if hasattr(widget, 'update_theme'):
                        widget.update_theme(self.theme)
                else:
                    # Doğrudan yüklenmiş widget
                    if hasattr(widget, 'update_theme'):
                        widget.update_theme(self.theme)
                    elif hasattr(widget, '_apply_global_style'):
                        widget.theme = self.theme
                        widget._apply_global_style()
        except Exception as e:
            logger.error("Sayfa temaları güncellenemedi: %s", e)
            raise
    
    def _on_settings_changed(self, mode: str, color: str, expanded: bool, logo: str):
        """Ayarlar değiştiğinde (Sistem Ayarları sayfasından)"""
        try:
            needs_restart = (expanded != self.expanded_mode)
            
            self.current_mode = mode
            self.current_color = color
            self.expanded_mode = expanded
            self.logo_path = logo if logo else None
            
            self.theme = build_theme(mode, color)
            self._apply_theme()
            
            # Sidebar güncelle
            self.sidebar.set_dark_mode(mode == "dark")
            self.sidebar.update_theme(self.theme)
            self.sidebar.set_logo(self.logo_path)
            
            # Header güncelle
            self.header.update_theme(self.theme)
            
            # Sayfaların temasını güncelle (yeniden oluşturmadan)
            self._update_page_themes()

            self._save_settings()

            if needs_restart:
                QMessageBox.information(
                    self,
                    "Menü Stili",
                    "Menü stili değişikliği için uygulamayı yeniden başlatın."
                )
        except Exception as e:
            logger.error("Ayarlar uygulanamadı: %s", e)
            QMessageBox.critical(self, "Ayar Hatası", f"Ayarlar uygulanamadı:\n\n{str(e)}")
    
    def _toggle_sidebar(self):
        """Sidebar'ı gizle/göster"""
        try:
            if self.sidebar.isVisible():
                self.sidebar.hide()
            else:
                self.sidebar.show()
        except Exception as e:
            logger.error("Sidebar toggle hatası: %s", e)
    
    def closeEvent(self, event):
        """Pencere kapanırken"""
        # PDKS servisini durdur
        if PDKS_SERVICE_AVAILABLE:
            try:
                stop_pdks_service()
                logger.info("PDKS Reader Service durduruldu")
            except Exception as e:
                logger.warning("PDKS servisi durdurulurken hata: %s", e)

        # PLC Sync servisini durdur
        if PLC_SYNC_AVAILABLE:
            try:
                stop_plc_sync_service()
                logger.info("PLC Sync Service durduruldu")
            except Exception as e:
                logger.warning("PLC Sync servisi durdurulurken hata: %s", e)

        event.accept()


def main():
    """Ana fonksiyon"""
    # Komut satırı argümanlarını parse et
    args = parse_arguments()
    
    try:
        app = QApplication(sys.argv)
        app.setFont(QFont("Segoe UI", 10))
        
        # Fusion style - cross-platform tutarlılık için
        app.setStyle("Fusion")
        
        # Başlangıçta koyu tema palette (login için) - TÜM DURUMLAR
        from PySide6.QtGui import QPalette, QColor
        
        # Renk tanımları (PRAXIS kurumsal lacivert-siyah)
        bg_window = QColor("#151B23")
        bg_base = QColor("#232C3B")
        bg_alt = QColor("#1C2430")
        text_color = QColor("#E8ECF1")
        text_secondary = QColor("#8896A6")
        text_disabled = QColor("#3A4555")
        border_color = QColor("#1E2736")
        primary = QColor("#C41E1E")
        
        dark_palette = QPalette()
        
        # === ACTIVE STATE ===
        dark_palette.setColor(QPalette.Active, QPalette.Window, bg_window)
        dark_palette.setColor(QPalette.Active, QPalette.WindowText, text_color)
        dark_palette.setColor(QPalette.Active, QPalette.Base, bg_base)
        dark_palette.setColor(QPalette.Active, QPalette.AlternateBase, bg_alt)
        dark_palette.setColor(QPalette.Active, QPalette.Text, text_color)
        dark_palette.setColor(QPalette.Active, QPalette.Button, bg_base)
        dark_palette.setColor(QPalette.Active, QPalette.ButtonText, text_color)
        dark_palette.setColor(QPalette.Active, QPalette.BrightText, QColor('#FFFFFF'))
        dark_palette.setColor(QPalette.Active, QPalette.Highlight, primary)
        dark_palette.setColor(QPalette.Active, QPalette.HighlightedText, QColor('#FFFFFF'))
        dark_palette.setColor(QPalette.Active, QPalette.Link, primary)
        dark_palette.setColor(QPalette.Active, QPalette.LinkVisited, primary)
        dark_palette.setColor(QPalette.Active, QPalette.ToolTipBase, bg_window)
        dark_palette.setColor(QPalette.Active, QPalette.ToolTipText, text_color)
        dark_palette.setColor(QPalette.Active, QPalette.PlaceholderText, text_secondary)
        dark_palette.setColor(QPalette.Active, QPalette.Light, bg_alt)
        dark_palette.setColor(QPalette.Active, QPalette.Midlight, bg_alt)
        dark_palette.setColor(QPalette.Active, QPalette.Dark, border_color)
        dark_palette.setColor(QPalette.Active, QPalette.Mid, border_color)
        dark_palette.setColor(QPalette.Active, QPalette.Shadow, QColor('#000000'))
        
        # === INACTIVE STATE ===
        dark_palette.setColor(QPalette.Inactive, QPalette.Window, bg_window)
        dark_palette.setColor(QPalette.Inactive, QPalette.WindowText, text_color)
        dark_palette.setColor(QPalette.Inactive, QPalette.Base, bg_base)
        dark_palette.setColor(QPalette.Inactive, QPalette.AlternateBase, bg_alt)
        dark_palette.setColor(QPalette.Inactive, QPalette.Text, text_color)
        dark_palette.setColor(QPalette.Inactive, QPalette.Button, bg_base)
        dark_palette.setColor(QPalette.Inactive, QPalette.ButtonText, text_color)
        dark_palette.setColor(QPalette.Inactive, QPalette.BrightText, QColor('#FFFFFF'))
        dark_palette.setColor(QPalette.Inactive, QPalette.Highlight, primary)
        dark_palette.setColor(QPalette.Inactive, QPalette.HighlightedText, QColor('#FFFFFF'))
        dark_palette.setColor(QPalette.Inactive, QPalette.Link, primary)
        dark_palette.setColor(QPalette.Inactive, QPalette.LinkVisited, primary)
        dark_palette.setColor(QPalette.Inactive, QPalette.ToolTipBase, bg_window)
        dark_palette.setColor(QPalette.Inactive, QPalette.ToolTipText, text_color)
        dark_palette.setColor(QPalette.Inactive, QPalette.PlaceholderText, text_secondary)
        dark_palette.setColor(QPalette.Inactive, QPalette.Light, bg_alt)
        dark_palette.setColor(QPalette.Inactive, QPalette.Midlight, bg_alt)
        dark_palette.setColor(QPalette.Inactive, QPalette.Dark, border_color)
        dark_palette.setColor(QPalette.Inactive, QPalette.Mid, border_color)
        dark_palette.setColor(QPalette.Inactive, QPalette.Shadow, QColor('#000000'))
        
        # === DISABLED STATE ===
        dark_palette.setColor(QPalette.Disabled, QPalette.Window, bg_window)
        dark_palette.setColor(QPalette.Disabled, QPalette.WindowText, text_disabled)
        dark_palette.setColor(QPalette.Disabled, QPalette.Base, bg_base)
        dark_palette.setColor(QPalette.Disabled, QPalette.AlternateBase, bg_alt)
        dark_palette.setColor(QPalette.Disabled, QPalette.Text, text_disabled)
        dark_palette.setColor(QPalette.Disabled, QPalette.Button, bg_base)
        dark_palette.setColor(QPalette.Disabled, QPalette.ButtonText, text_disabled)
        dark_palette.setColor(QPalette.Disabled, QPalette.BrightText, text_disabled)
        dark_palette.setColor(QPalette.Disabled, QPalette.Highlight, border_color)
        dark_palette.setColor(QPalette.Disabled, QPalette.HighlightedText, text_disabled)
        dark_palette.setColor(QPalette.Disabled, QPalette.Link, text_disabled)
        dark_palette.setColor(QPalette.Disabled, QPalette.LinkVisited, text_disabled)
        dark_palette.setColor(QPalette.Disabled, QPalette.ToolTipBase, bg_window)
        dark_palette.setColor(QPalette.Disabled, QPalette.ToolTipText, text_disabled)
        dark_palette.setColor(QPalette.Disabled, QPalette.PlaceholderText, text_disabled)
        dark_palette.setColor(QPalette.Disabled, QPalette.Light, bg_alt)
        dark_palette.setColor(QPalette.Disabled, QPalette.Midlight, bg_alt)
        dark_palette.setColor(QPalette.Disabled, QPalette.Dark, border_color)
        dark_palette.setColor(QPalette.Disabled, QPalette.Mid, border_color)
        dark_palette.setColor(QPalette.Disabled, QPalette.Shadow, QColor('#000000'))
        
        app.setPalette(dark_palette)
        
        # ─────────────────────────────────────────────
        # KOMUT SATIRI ARGÜMANLARI KONTROLÜ
        # ─────────────────────────────────────────────
        
        # --reset-db: Config'i sıfırla
        if args.reset_db:
            logger.info("Veritabanı ayarları sıfırlanıyor...")
            try:
                from core.external_config import config_manager, CONFIG_FILE
                import os
                if os.path.exists(CONFIG_FILE):
                    os.remove(CONFIG_FILE)
                    logger.info("%s silindi", CONFIG_FILE)
            except Exception as e:
                logger.warning("Config sıfırlama hatası: %s", e)
            args.setup = True  # Wizard'ı aç
        
        # --setup veya DB bağlantı hatası: Setup wizard aç
        if args.setup:
            logger.info("Setup wizard açılıyor...")
            if not show_setup_wizard(app, force=False):
                logger.info("Setup iptal edildi, uygulama kapatılıyor.")
                return
        
        # ─────────────────────────────────────────────
        # VERİTABANI BAĞLANTI KONTROLÜ (retry destekli)
        # ─────────────────────────────────────────────
        MAX_DB_RETRIES = 3
        db_ok = False

        for db_attempt in range(MAX_DB_RETRIES):
            db_ok, db_error = check_database_connection()

            if db_ok:
                break

            logger.warning("Veritabanı bağlantı hatası (deneme %d/%d): %s", db_attempt + 1, MAX_DB_RETRIES, db_error)

            # Kullanıcıya seçenek sun
            msg = QMessageBox(None)
            msg.setWindowTitle("Veritabanı Bağlantı Hatası")
            msg.setIcon(QMessageBox.Warning)
            msg.setText(
                f"Veritabanına bağlanılamadı:\n{db_error}"
            )
            msg.setInformativeText("Ne yapmak istersiniz?")

            btn_retry = msg.addButton("Tekrar Dene", QMessageBox.AcceptRole)
            btn_setup = msg.addButton("Ayarları Düzenle", QMessageBox.ActionRole)
            btn_exit = msg.addButton("Çıkış", QMessageBox.RejectRole)

            msg.setDefaultButton(btn_retry)
            msg.exec()

            clicked = msg.clickedButton()

            if clicked == btn_retry:
                # Bir sonraki döngü tekrar deneyecek
                continue
            elif clicked == btn_setup:
                if not show_setup_wizard(app, force=False):
                    logger.info("Setup iptal edildi.")
                    continue  # Wizard iptal olsa bile tekrar deneme şansı ver
                # Wizard başarılı, tekrar dene
                continue
            else:
                # Çıkış
                logger.info("Kullanıcı çıkışı seçti.")
                return

        if not db_ok:
            QMessageBox.critical(
                None,
                "Bağlantı Hatası",
                f"Veritabanına {MAX_DB_RETRIES} deneme sonra da bağlanılamadı.\n\n"
                "Lütfen ağ bağlantınızı ve sunucu durumunu kontrol edip\n"
                "uygulamayı tekrar başlatın."
            )
            return

        logger.info("Veritabanı bağlantısı başarılı")
        
        # ─────────────────────────────────────────────
        # GÜNCELLEME KONTROLÜ
        # ─────────────────────────────────────────────
        try:
            from core.updater import SelfUpdater
            updater = SelfUpdater()
            update_info = updater.check_for_updates()
            
            if update_info:
                # Güncelleme var, dialog göster
                if updater.show_update_dialog():
                    # Güncelleme başlatıldı, uygulama kapanacak
                    return
        except Exception as e:
            # Güncelleme kontrolü başarısız olsa bile uygulama çalışsın
            logger.warning("Güncelleme kontrolü hatası: %s", e)
        # ─────────────────────────────────────────────
        
        # ─────────────────────────────────────────────
        # SPLASH SCREEN → LOGIN → MAIN WINDOW
        # ─────────────────────────────────────────────
        # Splash kapanınca Qt uygulamayı kapatmasın (son pencere kapanma davranışı)
        app.setQuitOnLastWindowClosed(False)

        # MainWindow referansını sakla (garbage collection engellemek için)
        main_window_ref = []

        def on_splash_finished():
            """Splash animasyonu bittiğinde login göster."""
            splash.close()

            # Login
            try:
                login = ModernLoginDialog()
            except Exception as e:
                logger.critical("Login dialog oluşturulamadı: %s", e)
                show_error_dialog("Login Hatası", e)
                app.quit()
                return

            if login.exec() == ModernLoginDialog.Accepted:
                try:
                    # Login'den kullanıcı bilgisini al
                    user_info = ModernLoginDialog.get_current_user()

                    user_data = {
                        "id": user_info.get('id', 1),
                        "ad": user_info.get('fullname', '').split()[0] if user_info.get('fullname') else 'Kullanıcı',
                        "soyad": user_info.get('fullname', '').split()[-1] if user_info.get('fullname') and len(user_info.get('fullname', '').split()) > 1 else '',
                        "kullanici_adi": user_info.get('username', 'user'),
                        "roller": [{"kod": user_info.get('role', 'USER'), "ad": user_info.get('role', 'Kullanıcı')}]
                    }

                    # ─────────────────────────────────────────────
                    # THEMED MESSAGEBOX AKTİF ET
                    # ─────────────────────────────────────────────
                    if THEMED_MESSAGEBOX_AVAILABLE:
                        initial_theme = build_theme("dark", "redline")
                        patch_messagebox(initial_theme)
                    # ─────────────────────────────────────────────

                    # MainWindow açıldığında normal kapanma davranışına dön
                    app.setQuitOnLastWindowClosed(True)

                    window = MainWindow(user_data)
                    main_window_ref.append(window)  # GC engelle
                    window.showMaximized()

                    # Global RFID kart okuyucu servisini başlat
                    try:
                        from core.rfid_service import RFIDService
                        rfid_svc = RFIDService.instance()
                        rfid_svc.start()
                        logger.info("Global RFID servisi başlatıldı")
                    except Exception as rfid_err:
                        logger.warning("RFID servisi başlatılamadı: %s", rfid_err)

                except Exception as e:
                    logger.critical("Ana pencere oluşturulamadı: %s", e)
                    show_error_dialog("Ana Pencere Hatası", e)
                    traceback.print_exc()
                    app.quit()
            else:
                app.quit()

        # Splash screen göster ve yükleme animasyonu başlat
        splash = NexorSplashScreen()
        splash.show()
        splash.start_loading(on_splash_finished)

        sys.exit(app.exec())
    
    except Exception as e:
        logger.critical("Uygulama başlatılamadı: %s", e)
        traceback.print_exc()
        input("\n\nHata detaylarını okuyun. Kapatmak için Enter'a basın...")


if __name__ == "__main__":
    main()
